### ISSUE TITLE
Comparison on memories

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/seashell#55]
In #46, @sampsyo said:
> [comparisons] Should probably only be supported for primitive/numeric types (not memories, for example).

Should be not allow stuff like `a[0] == 0`? Constant comparisons might be fine, but what would this mean and what would the hardware look like:

```
for (...) unroll 3 {
  if (a[i] < 10) { a[i] := 1 }
}
```

(Search might require comparisons on dynamic memory locations)

**Comment by sampsyo** [comment]
Aha, over in #46, I did not mean to argue against allowing `a[0] == 0` because `a[0]` (presumably) has a primitive type. I just didn't want to support `a == b` where `a` and `b` are both memories.

I think that example looks OK—provided that we let the read and write to `a[i]` happen in separate logical timesteps. The hardware could contain both a read and write connection to `a`. It would could have three logical time stages:

1. Send the index for `i` to the memory `a` to read a value.
2. A comparator.
3. A write to `a` gated by an "and" so it only actually sends the message if the result of the comparison is true.
